from __future__ import annotations

import json
import logging
import subprocess
from dataclasses import dataclass, field
from html import escape
from pathlib import Path
from typing import Any

import yaml


ROOT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT_DIR / "src"
DOCS_DIR = ROOT_DIR / "docs"
ALGORITHMS_DOCS_DIR = DOCS_DIR / "algorithms"
GENERATED_ASSETS_DIR = DOCS_DIR / "assets" / "generated"
INDEX_DOC = DOCS_DIR / "index.md"
GENERATED_NOTICE = "<!-- Generated by scripts/generate_docs.py. Do not edit directly. -->"
REQUIRED_FIELDS = ("title", "slug", "summary", "category", "tags", "preferred_renderer")
VALID_RENDERERS = {"mermaid", "graphviz"}


@dataclass(slots=True)
class AlgorithmEntry:
    title: str
    slug: str
    summary: str
    category: str
    tags: list[str]
    preferred_renderer: str
    diagram_type: str
    diagram_path: Path
    source_dir: Path
    notes: list[str] = field(default_factory=list)
    formulas: list[tuple[str, str]] = field(default_factory=list)


def load_metadata(folder: Path) -> dict[str, Any] | None:
    meta_yaml = folder / "meta.yaml"
    meta_json = folder / "meta.json"

    try:
        if meta_yaml.exists():
            return yaml.safe_load(meta_yaml.read_text(encoding="utf-8")) or {}
        if meta_json.exists():
            return json.loads(meta_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, yaml.YAMLError) as exc:
        logging.warning("Skipping %s: metadata could not be read (%s)", folder.name, exc)
        return None

    logging.warning("Skipping %s: missing meta.yaml or meta.json", folder.name)
    return None


def discover_diagram(folder: Path) -> tuple[str, Path] | None:
    mermaid_file = folder / "diagram.mmd"
    graphviz_file = folder / "diagram.dot"

    if mermaid_file.exists():
        return "mermaid", mermaid_file
    if graphviz_file.exists():
        return "graphviz", graphviz_file

    logging.warning("Skipping %s: missing diagram.mmd or diagram.dot", folder.name)
    return None


def normalize_notes(raw_notes: Any) -> list[str]:
    if raw_notes is None:
        return []
    if isinstance(raw_notes, str):
        return [raw_notes.strip()] if raw_notes.strip() else []
    if isinstance(raw_notes, list):
        notes = [str(note).strip() for note in raw_notes if str(note).strip()]
        return notes
    logging.warning("Ignoring notes: expected a string or list, got %s", type(raw_notes).__name__)
    return []


def normalize_formulas(raw_formulas: Any) -> list[tuple[str, str]]:
    if raw_formulas is None:
        return []

    if isinstance(raw_formulas, str):
        formula = raw_formulas.strip()
        return [("", formula)] if formula else []

    if not isinstance(raw_formulas, list):
        logging.warning("Ignoring formulas: expected a string or list, got %s", type(raw_formulas).__name__)
        return []

    formulas: list[tuple[str, str]] = []

    for item in raw_formulas:
        if isinstance(item, str):
            formula = item.strip()
            if formula:
                formulas.append(("", formula))
            continue

        if isinstance(item, dict):
            label = str(item.get("label") or item.get("name") or item.get("title") or "").strip()
            expression = str(item.get("latex") or item.get("equation") or item.get("expression") or "").strip()
            if expression:
                formulas.append((label, expression))
            continue

        logging.warning("Ignoring formula entry: expected a string or mapping, got %s", type(item).__name__)

    return formulas


def validate_algorithm(folder: Path, data: dict[str, Any]) -> AlgorithmEntry | None:
    missing_fields = [field for field in REQUIRED_FIELDS if field not in data or data[field] in ("", None)]
    if missing_fields:
        logging.warning("Skipping %s: missing required fields %s", folder.name, ", ".join(missing_fields))
        return None

    tags = data["tags"]
    if not isinstance(tags, list) or not all(isinstance(tag, str) and tag.strip() for tag in tags):
        logging.warning("Skipping %s: tags must be a non-empty list of strings", folder.name)
        return None

    preferred_renderer = str(data["preferred_renderer"]).strip().lower()
    if preferred_renderer not in VALID_RENDERERS:
        logging.warning(
            "Skipping %s: preferred_renderer must be one of %s",
            folder.name,
            ", ".join(sorted(VALID_RENDERERS)),
        )
        return None

    diagram = discover_diagram(folder)
    if diagram is None:
        return None

    diagram_type, diagram_path = diagram
    return AlgorithmEntry(
        title=str(data["title"]).strip(),
        slug=str(data["slug"]).strip(),
        summary=str(data["summary"]).strip(),
        category=str(data["category"]).strip(),
        tags=[tag.strip() for tag in tags],
        preferred_renderer=preferred_renderer,
        diagram_type=diagram_type,
        diagram_path=diagram_path,
        source_dir=folder,
        notes=normalize_notes(data.get("notes")),
        formulas=normalize_formulas(data.get("formulas")),
    )


def discover_algorithms() -> list[AlgorithmEntry]:
    if not SRC_DIR.exists():
        logging.warning("Source directory %s does not exist", SRC_DIR)
        return []

    algorithms: list[AlgorithmEntry] = []

    for folder in sorted(path for path in SRC_DIR.iterdir() if path.is_dir() and not path.name.startswith(".")):
        metadata = load_metadata(folder)
        if metadata is None:
            continue

        algorithm = validate_algorithm(folder, metadata)
        if algorithm is not None:
            algorithms.append(algorithm)

    algorithms.sort(key=lambda item: item.title.lower())
    return algorithms


def ensure_output_dirs() -> None:
    ALGORITHMS_DOCS_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_ASSETS_DIR.mkdir(parents=True, exist_ok=True)


def render_mermaid_block(diagram_path: Path) -> str:
    diagram = diagram_path.read_text(encoding="utf-8").strip()
    return f"```mermaid\n{diagram}\n```"


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return

    path.write_text(content, encoding="utf-8")


def render_graphviz_block(algorithm: AlgorithmEntry) -> str:
    target_path = GENERATED_ASSETS_DIR / f"{algorithm.slug}.svg"

    try:
        completed = subprocess.run(
            ["dot", "-Tsvg", str(algorithm.diagram_path)],
            check=True,
            capture_output=True,
            text=True,
        )
        write_if_changed(target_path, completed.stdout)
        return f"![{algorithm.title} flowchart](../assets/generated/{algorithm.slug}.svg){{ .diagram-image }}"
    except FileNotFoundError:
        logging.warning(
            "Graphviz is not installed. Falling back to source display for %s.",
            algorithm.source_dir.name,
        )
    except subprocess.CalledProcessError as exc:
        logging.warning("Graphviz rendering failed for %s: %s", algorithm.source_dir.name, exc.stderr.strip())

    source = algorithm.diagram_path.read_text(encoding="utf-8").strip()
    return "\n".join(
        [
            '!!! warning "Graphviz preview unavailable"',
            "    Install the Graphviz `dot` CLI to convert `diagram.dot` into SVG during generation.",
            "",
            "```dot",
            source,
            "```",
        ]
    )


def render_algorithm_page(algorithm: AlgorithmEntry) -> str:
    tags = ", ".join(algorithm.tags)
    metadata_html = "\n".join(
        [
            '<div class="algorithm-meta">',
            f"  <span>{escape(algorithm.category)}</span>",
            f"  <span>{escape(tags)}</span>",
            f"  <span>{escape(algorithm.diagram_type.title())}</span>",
            "</div>",
        ]
    )

    notes_block = ""
    if algorithm.notes:
        notes_lines = "\n".join(f"- {note}" for note in algorithm.notes)
        notes_block = f"\n## Notes\n\n{notes_lines}\n"

    formulas_block = ""
    if algorithm.formulas:
        formula_sections: list[str] = []
        for label, expression in algorithm.formulas:
            if label:
                formula_sections.append("\n".join([f"### {label}", "", "$$", expression, "$$"]))
            else:
                formula_sections.append("\n".join(["$$", expression, "$$"]))
        formulas_block = f"\n## Formulas\n\n{'\n\n'.join(formula_sections)}\n"

    if algorithm.diagram_type == "mermaid":
        flowchart_block = render_mermaid_block(algorithm.diagram_path)
    else:
        flowchart_block = render_graphviz_block(algorithm)

    return "\n".join(
        [
            GENERATED_NOTICE,
            "",
            f"# {algorithm.title}",
            "",
            algorithm.summary,
            "",
            metadata_html,
            "",
            "## Flowchart",
            "",
            flowchart_block,
            formulas_block.rstrip(),
            notes_block.rstrip(),
            "",
            "[Back to homepage](../index.md){ .md-button .md-button--primary }",
            "",
        ]
    ).strip() + "\n"


def render_homepage(algorithms: list[AlgorithmEntry]) -> str:
    cards: list[str] = []

    for algorithm in algorithms:
        tags = " · ".join(escape(tag) for tag in algorithm.tags)
        cards.append(
            "\n".join(
                [
                    f'<a class="algorithm-card" href="algorithms/{escape(algorithm.slug)}/">',
                    f'  <p class="algorithm-card__category">{escape(algorithm.category)}</p>',
                    f"  <h2>{escape(algorithm.title)}</h2>",
                    f"  <p>{escape(algorithm.summary)}</p>",
                    f'  <p class="algorithm-card__tags">{tags}</p>',
                    "</a>",
                ]
            )
        )

    if not cards:
        cards_markup = (
            '<div class="algorithm-empty-state">'
            "No valid algorithm folders were found under <code>src/</code>."
            "</div>"
        )
    else:
        cards_markup = "\n".join(["<div class=\"algorithm-grid\">", *cards, "</div>"])

    return "\n".join(
        [
            GENERATED_NOTICE,
            "",
            "# Algorithm Flowcharts",
            "",
            '<div class="algorithm-lead">',
            "  <p>Reference pages generated from source diagrams under <code>src/</code>. "
            "Add a new folder with <code>meta.yaml</code> and a diagram file, then rebuild the site.</p>",
            "</div>",
            "",
            cards_markup,
            "",
        ]
    )


def prune_stale_files(expected_markdown: set[Path], expected_svgs: set[Path]) -> None:
    for path in ALGORITHMS_DOCS_DIR.glob("*.md"):
        if path not in expected_markdown:
            path.unlink()

    for path in GENERATED_ASSETS_DIR.glob("*.svg"):
        if path not in expected_svgs:
            path.unlink()


def write_generated_docs(algorithms: list[AlgorithmEntry]) -> None:
    ensure_output_dirs()
    write_if_changed(INDEX_DOC, render_homepage(algorithms))

    expected_markdown: set[Path] = set()
    expected_svgs: set[Path] = set()

    for algorithm in algorithms:
        target_file = ALGORITHMS_DOCS_DIR / f"{algorithm.slug}.md"
        expected_markdown.add(target_file)
        if algorithm.diagram_type == "graphviz":
            expected_svgs.add(GENERATED_ASSETS_DIR / f"{algorithm.slug}.svg")
        write_if_changed(target_file, render_algorithm_page(algorithm))

    prune_stale_files(expected_markdown, expected_svgs)


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    algorithms = discover_algorithms()
    write_generated_docs(algorithms)
    logging.info("Generated %s algorithm page(s).", len(algorithms))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
